# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

# Install SSH Key
# Install an SSH key prior to a build or release
- task: InstallSSHKey@0
  inputs:
    hostName: staging-26860.prod.hosting.acquia.com
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCvFwUM59KyCw/fMka6aNcbCEP0jpnQ4IYeY73GvM+VEPjKMZK+GZ5uIO+fmvFU2DJam4jBRaSnRk7hjFWfTRlGrt+3VklsV/lehYKgt/jKjp8tKtuTRUursX7guQhx1NUtdcjU9M2Ko1hTx/mxgNRPQPUp8ikZLjvb1HOxZzpLZVVvePBshskE08zMTyE3jOh1fpWmiRAyPwGf6BLRhMHqyAgmMJeQd0QVlvYZGRDGrMHERNGNdwb+7UxYjaT3Q5Jotx2c5QKnf73CyDpzwbHTeBK/+TXN1XLMMgJwbVFCPgZGSNKN0DymJB840/Z1LUDGMHESddyqHwXPNWY9zebxATG/PcikAikHF7T7t2TcCZQj2T8XwbpFLhA6d2awVF0WiWH+RStIXXPtCVkDWM7OQMUMVmse5aNbPw4tO4VnlSvoyau85vBi+d62KYcTY530WO//jIfNS3HAAaqZoHMqidH109NWT0oNXeqDfP7QDEvE90mlimBUECXYJk3Ve0CokreF7Fig5KmKP3h8Dx/8elccEEoI5zU9D/IAwXjKh50kqMQPmYIxno06Agi189qfO8Hi3yYJA7XmxnadLgPf5pRuPviPfUrP2N2nM9tKmVYSUt2O+jdndbCRwkpg28h102crljvLwzpF2fXqDM1e9lPtx9jXgEfwibJtgOOVMw== joshua.li@AMAC02W50L5HTDG'
    sshPassphrase: 'password'
    sshKeySecureFile: pipelines

# Download Secure File
# Download a secure file to a temporary location on the build or release agent
- task: DownloadSecureFile@1
  inputs:
    secureFile: acquiacli.yml

- script: mv $(Agent.TempDirectory)/acquiacli.yml ./
  displayName: 'Move cli data.'

- script: |
    rm -rf .gitignore
    cp .gitignore-prod ./.gitignore
  displayName: 'Rename git ignore file.'

- script: |
    sudo apt-get remove composer
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('SHA384', 'composer-setup.php') === '93b54496392c062774670ac18b134c3b3a95e5a5e5c8f1a9f115f203b75bf9a129d5daa8ba6a13e2cc8a1da0806388a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"
    sudo mv composer.phar /usr/local/bin/composer
    composer --version
  displayName: 'Update composer'

#- script: composer install --no-interaction --prefer-dist
  #displayName: 'composer install'

- script: |
    git config --global user.email "oasislrjjrj@gmail.com"
    git config --global user.name "Joshua Li"
    git remote add acquia jldemo@svn-5468.devcloud.hosting.acquia.com:jldemo.git
    git fetch acquia
    git add .
    git commit -m 'Release1'
    git tag release1
    git push acquia release1 -f --tags
  displayName: 'Push to Acquia'

- script: ./vendor/bin/acquiacli preprod:deploy jldemo.dev dev release1 true
  displayName: 'Deploy to Acquia'

- script: |
    ./vendor/bin/drush @dev state-set system.maintenance_mode 1
    ./vendor/bin/drush @dev cr
    ./vendor/bin/drush @dev updb
    ./vendor/bin/drush @dev cim ../config/default
    ./vendor/bin/drush @dev cr
    ./vendor/bin/drush @dev state-set system.maintenance_mode 0
  displayName: 'Update configuration'


