language: php

sudo: false

php:
  - 5.6
  - 7

matrix:
  fast_finish: true

env:

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Update composer.
  - composer self-update
  - composer --version
  # Add the oauth token to prevent GitHub timeouts.
#  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Let Composer do all the magic!
  - composer install
  # Install Standard profile.
  - cd docroot
  - drush site-install standard --yes --account-pass=admin --db-url=mysql://root:@localhost/drupal
  - drush config-set system.performance css.preprocess 0 --yes --format=boolean
  - drush config-set system.performance js.preprocess 0 --yes --format=boolean
  - drush config-set system.logging error_level all --yes
  # These directories are not created by default and Drupal will be angry without them!
  - mkdir $TRAVIS_BUILD_DIR/docroot/profiles
  - mkdir $TRAVIS_BUILD_DIR/docroot/themes

before_script:
  - drush runserver --default-server=builtin 8888 &>/dev/null &
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - mkdir $TRAVIS_BUILD_DIR/docroot/modules/contrib/cloudflare
  - rsync --exclude-from=$TRAVIS_BUILD_DIR/docroot $TRAVIS_BUILD_DIR/ $TRAVIS_BUILD_DIR/docroot/modules/contrib/cloudflare
  - cd $TRAVIS_BUILD_DIR/docroot/modules/contrib/cloudflare
  - phpcs $TRAVIS_BUILD_DIR/docroot/modules/contrib/cloudflare --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=bin,*.css,libraries,modules/contrib
  - cd $TRAVIS_BUILD_DIR/docroot
  - drush en simpletest cloudflare --yes
  - php core/scripts/run-tests.sh --module cloudflare --php $(which php) --url http://localhost:8888/ --verbose
