site_settings.config:
  type: config_object
  label: 'Site Settings config'
  mapping:
    template_key:
      type: string
      label: 'The key at which site settings should be made available in templates'
